$(document).ready(function(){
    var owl = $('.owl-carousel');
    owl.owlCarousel({
        loop:true,
        dots:true,
        mouseDrag:true,
        touchDrag:true,
        margin:10,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },            
            1200:{
                items:3
            }
        }
    });
});